import * as fs from 'fs';
import * as path from 'path';
import { type VerificationResult, countErrors, countWarnings } from './bundle.js';

/**
 * Generate a markdown snippet suitable for a GitHub PR description.
 * Uses relative paths for screenshots (assumes artifacts are committed or linked).
 */
export function formatForPR(result: VerificationResult): string {
  const projectName = path.basename(process.cwd());
  const durationSec = Math.round(result.durationMs / 1000);

  let totalErrors = 0;
  let totalWarnings = 0;

  let md = `## Visual Verification — ProofShot

| Page | Status | Screenshot |
|------|--------|------------|
`;

  for (const page of result.pageResults) {
    const errors = countErrors(page.errors);
    const warnings = countWarnings(page.consoleOutput);
    totalErrors += errors;
    totalWarnings += warnings;

    const status = errors > 0 ? '⚠️ Errors' : '✅ OK';
    const relativeSS = path.relative(process.cwd(), page.screenshotPath);
    md += `| \`${page.page}\` | ${status} | ![${page.page}](${relativeSS}) |\n`;
  }

  md += `
**Framework:** ${result.framework} | **Pages:** ${result.pageResults.length} | **Errors:** ${totalErrors} | **Warnings:** ${totalWarnings} | **Duration:** ${durationSec}s
`;

  if (result.videoPath) {
    const relativeVideo = path.relative(process.cwd(), result.videoPath);
    md += `\n**Video:** [Session recording](${relativeVideo})\n`;
  }

  md += `\n<sub>Generated by [ProofShot](https://github.com/proofshot/proofshot)</sub>\n`;

  return md;
}

/**
 * Write PR-formatted output to a file or stdout.
 */
export function writePRFormat(
  result: VerificationResult,
  outputPath?: string,
): string {
  const md = formatForPR(result);
  if (outputPath) {
    fs.writeFileSync(outputPath, md);
    return outputPath;
  }
  return md;
}
